baseURI = "https://complex.example.com/laderr#"
createdBy = ["Alice", "Bob", "Charlie"]
createdOn = "2025-01-17T12:00:01Z"
description = "A complex specification for testing all LaDeRR rules with SHACL compliance."
modifiedOn = "2025-01-18T12:00:02Z"
title = "Complex LaDeRR Specification"
version = "2.0"

[Entity.o1]
label = "Primary Entity"
capabilities = ["c1"]
vulnerabilities = ["v1"]

[Entity.o2]
label = "Secondary Entity"
capabilities = ["c2"]

[Entity.o3]
label = "Tertiary Entity"
capabilities = ["c3"]

[Capability.c1]
label = "Capability 1"
description = "Provides core functionality."

[Capability.c2]
label = "Capability 2"
description = "Disables vulnerabilities."
disables = ["v1", "c1"]

[Capability.c3]
label = "Capability 3"
description = "Exploits vulnerabilities."
exploits = "v1"

[Vulnerability.v1]
label = "Vulnerability 1"
description = "A vulnerability exploitable by c3 and mitigated by c2."
state = "enabled"
exposes = "c1"