baseURI = "https://teste.teste#"
createdBy = "Pedro Paulo F. Barcelos"
createdOn = "2025-02-10T14:30:00Z"
description = "A socio-ecological system model for flood risk and resilience."
scenario = "operational"
title = "Flood Risk and Resilience Model"
version = "1.1"

[Capability.flooding_potential]
description = "The river's potential to overflow and flood surrounding areas."
exploits = "weak_levees"
label = "Flooding Potential"
state = "enabled"

[Capability.water_control]
description = "Regulates water levels, mitigating flood risks."
disables = ["outdated_pumps", "weak_levees"]
label = "Water Flow Control"
state = "disabled"

[Capability.levee_reinforcement]
description = "A capability that strengthens Riverford’s levees to prevent flood risks."
disables = "weak_levees"
label = "Levee Reinforcement"
state = "enabled"

[Capability.housing]
description = "The housing infrastructure of Riverford, which needs flood protection."
label = "Housing Infrastructure"
state = "enabled"

[Vulnerability.weak_levees]
description = "A vulnerability in Riverford’s levees that can be exploited by the river’s flooding potential."
exposes = "housing"
label = "Weak Levees"
state = "enabled"

[Vulnerability.outdated_pumps]
description = "A vulnerability where outdated pumps cannot efficiently handle floodwaters."
exposes = "housing"
label = "Outdated Pumps"
state = "enabled"
