baseUri = "https://socio-ecological.example.com/laderr#"
createdBy = "Pedro Paulo F. Barcelos"
createdOn = "2025-02-10T14:30:00Z"
description = "A socio-ecological system model for flood risk and resilience."
title = "Flood Risk and Resilience Model"
version = "1.1"

[Vulnerability.weak_levees]
description = "A vulnerability in Riverford’s levees that can be exploited by the river’s flooding potential."
exposes = "housing"
label = "Weak Levees"
state = "enabled"
topObjectProperty = "housing"

[Vulnerability.outdated_pumps]
description = "A vulnerability where outdated pumps cannot efficiently handle floodwaters."
exposes = "housing"
label = "Outdated Pumps"
state = "enabled"
topObjectProperty = "housing"

[Capability.flooding_potential]
description = "The river's potential to overflow and flood surrounding areas."
exploits = "weak_levees"
label = "Flooding Potential"
state = "enabled"

[Capability.levee_reinforcement]
description = "A capability that strengthens Riverford’s levees to prevent flood risks."
disables = "weak_levees"
label = "Levee Reinforcement"
state = "enabled"
sustains = "RJJ"

[Capability.water_control]
description = "Regulates water levels, mitigating flood risks."
disables = ["outdated_pumps", "weak_levees"]
label = "Water Flow Control"
state = "enabled"
sustains = "RLM"

[Capability.housing]
description = "The housing infrastructure of Riverford, which needs flood protection."
label = "Housing Infrastructure"
state = "enabled"

[Entity.reinforcement_team]
capabilities = "levee_reinforcement"
label = "Levee Reinforcement Team"
protects = "riverford"
topObjectProperty = "riverford"

[Entity.silverstream]
capabilities = "flooding_potential"
label = "Silverstream River"
threatens = "riverford"

[Entity.greenridge_dam]
capabilities = "water_control"
label = "Greenridge Dam"
protects = "riverford"
topObjectProperty = "riverford"

[Entity.riverford]
capabilities = "housing"
label = "City of Riverford"
resiliences = ["RJJ", "RLM"]
vulnerabilities = ["outdated_pumps", "weak_levees"]

[Resilience.RLM]
preserves = "housing"
preservesAgainst = "flooding_potential"
preservesDespite = "weak_levees"
topObjectProperty = "flooding_potential"

[Resilience.RJJ]
preserves = "housing"
preservesAgainst = "flooding_potential"
preservesDespite = "weak_levees"
topObjectProperty = "flooding_potential"
