baseUri = "https://complex.example.com/laderr#"
createdBy = ["Alice", "Bob", "Charlie"]
createdOn = "2025-01-17T12:00:01Z"
description = "A complex specification for testing all LaDeRR rules with SHACL compliance."
modifiedOn = "2025-01-18T12:00:02Z"
title = "Complex LaDeRR Specification"
version = "2.0"

[Object.o3]
capabilities = "c3"
label = "Tertiary Object"
threatens = "o1"

[Object.o2]
capabilities = "c2"
inhibits = "o1"
label = "Secondary Object"
protects = "o1"

[Object.o1]
capabilities = "c1"
label = "Primary Object"
resiliences = "RAD"
vulnerabilities = "v1"

[Capability.c3]
description = "Exploits vulnerabilities."
exploits = "v1"
label = "Capability 3"
state = "enabled"

[Capability.c2]
description = "Disables vulnerabilities."
disables = ["c1", "v1"]
label = "Capability 2"
state = "enabled"
sustains = "RAD"

[Capability.c1]
description = "Provides core functionality."
label = "Capability 1"
state = "enabled"

[Vulnerability.v1]
description = "A vulnerability exploitable by c3 and mitigated by c2."
exposes = "c1"
label = "Vulnerability 1"
state = "enabled"

[Resilience.RAD]
preserves = "c1"
preservesAgainst = "c3"
preservesDespite = "v1"
