baseURI = "https://teste.teste#"
createdBy = "Pedro Paulo F. Barcelos"
createdOn = "2025-02-10T14:30:00Z"
description = "A socio-ecological system model for flood risk and resilience."
scenario = "operational"
title = "Flood Risk and Resilience Model"
version = "1.1"

[Asset.riverford]
capabilities = "housing"
label = "riverford"
resiliences = ["R7G", "RLK"]
vulnerabilities = ["outdated_pumps", "weak_levees"]

[Capability.flooding_potential]
description = "The river's potential to overflow and flood surrounding areas."
exploits = "weak_levees"
label = "Flooding Potential"
state = "enabled"

[Capability.housing]
description = "The housing infrastructure of Riverford, which needs flood protection."
label = "Housing Infrastructure"
state = "enabled"

[Capability.levee_reinforcement]
description = "A capability that strengthens Riverford’s levees to prevent flood risks."
disables = "weak_levees"
label = "Levee Reinforcement"
state = "enabled"
sustains = "RLK"

[Capability.water_control]
description = "Regulates water levels, mitigating flood risks."
disables = ["outdated_pumps", "weak_levees"]
label = "Water Flow Control"
state = "enabled"
sustains = "R7G"

[Control.greenridge_dam]
capabilities = "water_control"
inhibits = "silverstream"
label = "Greenridge Dam"
protects = "riverford"

[Control.reinforcement_team]
capabilities = "levee_reinforcement"
inhibits = "silverstream"
label = "Levee Reinforcement Team"
protects = "riverford"

[Resilience.RLK]
label = "RLK"
preserves = "housing"
preservesAgainst = "flooding_potential"
preservesDespite = "weak_levees"

[Resilience.R7G]
label = "R7G"
preserves = "housing"
preservesAgainst = "flooding_potential"
preservesDespite = "weak_levees"

[Threat.silverstream]
capabilities = "flooding_potential"
failedToDamage = "riverford"
label = "Silverstream River"
threatens = "riverford"

[Vulnerability.weak_levees]
description = "A vulnerability in Riverford’s levees that can be exploited by the river’s flooding potential."
exposes = "housing"
label = "Weak Levees"
state = "disabled"

[Vulnerability.outdated_pumps]
description = "A vulnerability where outdated pumps cannot efficiently handle floodwaters."
exposes = "housing"
label = "Outdated Pumps"
state = "disabled"
