baseUri = "https://example123.com/laderr#"
createdBy = ["Alice", "Bob", ]
createdOn = 2025-01-17T12:00:00Z
description = "This is an example specification for LaDeRR."
modifiedOn = 2025-01-18T12:00:00Z
title = "Example LaDeRR Specification"
version = "1.0"

[RiskEvent.a]
label = "Test Risk Event"
description = "A risk event example."

[Object.b1]
label = "Test Object"
description = "An object involved in the risk."
capabilities = ["c1", "c2", "d1"]  # List of capability IDs
vulnerabilities = ["v1", "v2", "d1"]  # List of disposition IDs

[Capability.c1]
label = "Capability 1"
description = "A capability of the object."

[Capability.c2]
label = "Capability 2"
description = "Another capability of the object."

[Vulnerability.v1]
label = "Vulnerability 1"
state = "enabled"
description = "A vulnerability associated with the object."

[Vulnerability.v2]
label = "Vulnerability 2"
state = "disabled"
description = "Another vulnerability associated with the object."

[Capability.d1]
[Vulnerability.d1]
label = "Shared Capability and Vulnerability"
description = "This object serves as both a capability and a vulnerability."