# Metadata Section
title = "Example LaDeRR Specification"
description = "This is an example specification for LaDeRR."
version = "1.0"
createdBy = ["Alice", "Bob"]
createdOn = 2025-01-17T12:00:00Z
modifiedOn = 2025-01-18T12:00:00Z
baseURI = "https://example123.com/laderr#"

# Data Section
[RiskEvent.a]
label = "Test Risk Event"
description = "A risk event example."

[Entity.b]
id = "b1"
label = "Test Entity"
description = "An entity involved in the risk."

[Disposition.c]
description = "A disposition example."
