baseURI = "https://supplychainresilience.laderr#"
createdBy = ["Pedro Paulo F. Barcelos"]
createdOn = "2025-06-09T12:00:00Z"
modifiedOn = "2025-06-14T00:00:00Z"
title = "Resilient Scenario – Mitigation of Geopolitical Threat via Inventory Management"
version = "1.0"
description = "This LaDeRR specification models a resilient supply chain scenario in which a dedicated inventory management capability neutralizes the stockout vulnerability caused by geopolitical instability, preserving production capability and preventing disruption."

[Scenario.component_disruption]
label = "Component Disruption Risk"
description = "Scenario where inventory management successfully mitigates geopolitical disruption risk, resulting in a resilient configuration."

[Entity.manufacturing_company]
label = "Manufacturing Company"
description = "Company responsible for producing and assembling critical components."
capabilities = ["critical_component_production"]
vulnerabilities = ["component_stockout_risk"]

[Entity.supply_chain_management_team]
label = "Supply Chain Management Team"
description = "Team dedicated to managing inventory and ensuring continuous component availability."
capabilities = ["inventory_management"]

[Entity.geopolitical_instability]
label = "Geopolitical Instability"
description = "Threat entity representing disruptions caused by trade embargoes or instability in supplier countries."
capabilities = ["disruption_capability"]

[Capability.disruption_capability]
label = "Disruption Capability"
description = "Capability of geopolitical threat to exploit vulnerabilities leading to disruptions."
exploits = ["component_stockout_risk"]

[Capability.critical_component_production]
label = "Critical Component Production"
description = "Ability to produce or source critical components efficiently."

[Capability.inventory_management]
label = "Inventory Management"
description = "Maintaining buffer stocks to mitigate stockouts."
disables = "component_stockout_risk"

[Vulnerability.component_stockout_risk]
label = "Component Stockout Risk"
description = "Vulnerability related to delays or unavailability of critical components."
exposes = ["critical_component_production"]